[tool_alias]
mammouth = "github:mammouth-ai/code"

[tools]
atuin = "latest"
bat = "latest"
bottom = "latest"
carapace = "latest"
chezmoi = "latest"
difftastic = "latest"
dotnet = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gdu = "latest"
gh = "latest"
gum = "latest"
jj = "latest"
imagemagick = "latest"
lazygit = "latest"
mammouth = { version = "latest", matching = "mammouth" }
micromamba = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
pi = "latest"
powershell = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
vivid = "latest"
yazi = "latest"
zoxide = "latest"
"aqua:fish-shell/fish-shell" = "latest"

[settings]
experimental = true
lockfile = true
trusted_config_paths = ["/"]
