[tool_alias]
mammouth = "github:mammouth-ai/code"

[tools]
atuin = "latest"
bat = "latest"
carapace = "latest"
difftastic = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gum = "latest"
jj = "latest"
mammouth = { version = "latest", matching = "mammouth" }
neovim = "latest"
opencode = "latest"
pi = "latest"
powershell = "latest"
ripgrep = "latest"
starship = "latest"
vivid = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
experimental = true
lockfile = true
trusted_config_paths = ["/"]
