[tool_alias]
mammouth = "mammouth-ai/code"

[tools]
"atuinsh/atuin" = "latest"
"sharkdp/bat" = "latest"
"ClementTsang/bottom" = "latest"
"carapace-sh/carapace-bin" = "latest"
"twpayne/chezmoi" = "latest"
"Wilfred/difftastic" = "latest"
"dotnet/dotnet" = "latest"
"eza-community/eza" = "latest"
"fastfetch-cli/fastfetch" = "latest"
"sharkdp/fd" = "latest"
"junegunn/fzf" = "latest"
"dundee/gdu" = "latest"
"cli/cli" = "latest"
"charmbracelet/gum" = "latest"
"jj-vcs/jj" = "latest"
"ImageMagick/ImageMagick" = "latest"
"jesseduffield/lazygit" = "latest"
"yshavit/mdq" = "latest"
"mammouth-ai/code" = "latest"
"mamba-org/mamba" = "latest"
"neovim/neovim" = "latest"
"nodejs/node" = "lts"
"anomalyco/opencode" = "latest"
"earendil-works/pi" = "latest"
"PowerShell/PowerShell" = "latest"
"python/cpython" = "latest"
"BurntSushi/ripgrep" = "latest"
"starship/starship" = "latest"
"astral-sh/uv" = "latest"
"sharkdp/vivid" = "latest"
"sxyazi/yazi" = "latest"
"ajeetdsouza/zoxide" = "latest"
"fish-shell/fish-shell" = "latest"
"tinted-theming/tinty" = "latest"
mammouth = { version = "latest", matching = "mammouth" }

[settings]
experimental = true
lockfile = true
trusted_config_paths = ["/"]
