# Generated by Set-TaminaruTheme - active catppuccin flavor: frappe
Set-PSReadLineOption -Colors @{
    "Default"            = '[38;2;198;208;245m'
    "Selection"          = '[48;2;65;69;89m'
    "Command"            = '[38;2;140;170;238m'
    "Parameter"          = '[38;2;238;190;190m'
    "Variable"           = '[38;2;238;190;190m'
    "String"             = '[38;2;166;209;137m'
    "Operator"           = '[38;2;244;184;228m'
    "Comment"            = '[38;2;131;139;167m'
    "Keyword"            = '[38;2;231;130;132m'
    "Number"             = '[38;2;239;159;118m'
    "Type"               = '[38;2;186;187;241m'
    "Member"             = '[38;2;129;200;190m'
    "Error"              = '[38;2;231;130;132m'
    "Emphasis"           = '[38;2;229;200;144m'
    "ContinuationPrompt" = '[38;2;153;209;219m'
    "InlinePrediction"   = '[38;2;115;121;148m'
}

$env:FZF_DEFAULT_OPTS = "--color=bg+:414559,bg:303446,spinner:f2d5cf,hl:e78284 --color=fg:c6d0f5,header:e78284,info:ca9ee6,pointer:f2d5cf --color=marker:babbf1,fg+:c6d0f5,prompt:ca9ee6,hl+:e78284 --color=selected-bg:51576d --color=border:737994,label:c6d0f5"
$env:BAT_THEME = "Catppuccin Frappe"

# vivid ships catppuccin-latte/frappe/macchiato/mocha themes out of the box
if (Get-Command vivid -ErrorAction SilentlyContinue) {
    $env:LS_COLORS = (vivid generate catppuccin-frappe 2>$null)
}
