[character]
success_symbol = "[ 🎏](bold green)"
error_symbol = "[ 👹](bold red)"
[git_branch]
symbol = "🌿 "
style = "bold yellow"
[time]
format = "%H:%M:%S"
style = "bold blue"
[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
[hostname]
ssh_only = true
format = "[@$hostname](bold green)"
[directory]
style = "bold green"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"
[git_status]
conflicted = "💣"
ahead = "📤"
behind = "📥"
diverged = "😵"
untracked = "🤷"
stashed = "📦"
modified = "✏️ "
staged = "📦"
renamed = "🔄"
deleted = "🗑️ "
style = "bold red"
[docker_context]
symbol = " 🐳 "
style = "bold blue"
format = "[$symbol$context]($style)"

