#!/usr/bin/env bash
# psreadline-hook.sh — Generate PowerShell theme.ps1 from the active base16 scheme
# Called by tinty after applying a theme.
set -euo pipefail

SCHEME_DIR="${HOME}/.local/share/tinted-theming/schemes"
SCHEME_FILE="${SCHEME_DIR}/$(tinty current 2>/dev/null).yaml"

if [ ! -f "$SCHEME_FILE" ]; then
    CURRENT=$(cat "${HOME}/.local/share/tinted-theming/tinty/artifacts/current_scheme" 2>/dev/null || echo "")
    if [ -n "$CURRENT" ]; then
        SCHEME_FILE="${SCHEME_DIR}/${CURRENT}.yaml"
    fi
fi

if [ ! -f "$SCHEME_FILE" ]; then
    echo "[psreadline-hook] scheme file not found, skipping" >&2
    exit 0
fi

# Parse base16 colors
eval "$(grep -E '^base[0-9a-f]{2}:' "$SCHEME_FILE" | sed 's/: /="/;s/$/"/')"

# Map base16 to semantic roles
declare -A C=(
    [bg]="${base00:-303446}"
    [fg]="${base05:-c6d0f5}"
    [red]="${base08:-e78284}"
    [orange]="${base09:-ef9f76}"
    [yellow]="${base0A:-e5c890}"
    [green]="${base0B:-a6d189}"
    [cyan]="${base0C:-81c8be}"
    [blue]="${base0D:-8caaee}"
    [magenta]="${base0E:-ca9ee6}"
    [comments]="${base03:-737994}"
    [selection]="${base02:-414559}"
    [bright_fg]="${base04:-a5adce}"
)

hex_to_rgb() {
    local hex="$1"
    printf "%d,%d,%d" "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

ansi_fg() {
    local r g b
    IFS=',' read -r r g b <<< "$(hex_to_rgb "$1")"
    printf '\e[38;2;%d;%d;%dm' "$r" "$g" "$b"
}

ansi_bg() {
    local r g b
    IFS=',' read -r r g b <<< "$(hex_to_rgb "$1")"
    printf '\e[48;2;%d;%d;%dm' "$r" "$g" "$b"
}

# Build FZF_DEFAULT_OPTS
FZF_OPTS="--color=bg+:#${C[selection]},bg:#${C[bg]},spinner:#${C[cyan]},hl:#${C[red]}"
FZF_OPTS="$FZF_OPTS --color=fg:#${C[fg]},header:#${C[red]},info:#${C[magenta]},pointer:#${C[cyan]}"
FZF_OPTS="$FZF_OPTS --color=marker:#${C[blue]},fg+:#${C[fg]},prompt:#${C[magenta]},hl+:#${C[red]}"
FZF_OPTS="$FZF_OPTS --color=selected-bg:#${C[selection]} --color=border:#${C[comments]},label:#${C[fg]}"

# Detect scheme name for bat
SCHEME_NAME=$(tinty current 2>/dev/null || echo "")
BAT_THEME="ansi"

PWSH_THEME="# Generated by tinty psreadline-hook — do not edit manually
Set-PSReadLineOption -Colors @{
    \"Default\"            = '$(ansi_fg "${C[fg]}")'
    \"Selection\"          = '$(ansi_bg "${C[selection]}")'
    \"Command\"            = '$(ansi_fg "${C[blue]}")'
    \"Parameter\"          = '$(ansi_fg "${C[cyan]}")'
    \"Variable\"           = '$(ansi_fg "${C[cyan]}")'
    \"String\"             = '$(ansi_fg "${C[green]}")'
    \"Operator\"           = '$(ansi_fg "${C[magenta]}")'
    \"Comment\"            = '$(ansi_fg "${C[comments]}")'
    \"Keyword\"            = '$(ansi_fg "${C[red]}")'
    \"Number\"             = '$(ansi_fg "${C[orange]}")'
    \"Type\"               = '$(ansi_fg "${C[magenta]}")'
    \"Member\"             = '$(ansi_fg "${C[cyan]}")'
    \"Error\"              = '$(ansi_fg "${C[red]}")'
    \"Emphasis\"           = '$(ansi_fg "${C[yellow]}")'
    \"ContinuationPrompt\" = '$(ansi_fg "${C[cyan]}")'
    \"InlinePrediction\"   = '$(ansi_fg "${C[comments]}")'
}

\$env:FZF_DEFAULT_OPTS = \"$FZF_OPTS\"
\$env:BAT_THEME = \"$BAT_THEME\"

# vivid theme
if (Get-Command vivid -ErrorAction SilentlyContinue) {
    \$env:LS_COLORS = (vivid generate base16 2>\$null)
}
"

PWSH_DIR="${HOME}/.config/powershell"
mkdir -p "$PWSH_DIR"
echo "$PWSH_THEME" > "${PWSH_DIR}/theme.ps1"

echo "[psreadline-hook] powershell/theme.ps1 updated" >&2
