#!/usr/bin/env bash
# starship-hook.sh — Generate starship.toml from the active base16 scheme
# Called by tinty after applying a theme.
set -euo pipefail

SCHEME_DIR="${HOME}/.local/share/tinted-theming/schemes"
SCHEME_FILE="${SCHEME_DIR}/$(tinty current 2>/dev/null).yaml"

# If tinty isn't available or scheme file doesn't exist, try reading from artifacts
if [ ! -f "$SCHEME_FILE" ]; then
    CURRENT=$(cat "${HOME}/.local/share/tinted-theming/tinty/artifacts/current_scheme" 2>/dev/null || echo "")
    if [ -n "$CURRENT" ]; then
        SCHEME_FILE="${SCHEME_DIR}/${CURRENT}.yaml"
    fi
fi

if [ ! -f "$SCHEME_FILE" ]; then
    echo "[starship-hook] scheme file not found, skipping" >&2
    exit 0
fi

# Parse base16 scheme colors from YAML
# Format: base00: "1e1e2e" (without # prefix)
eval "$(grep -E '^base[0-9a-f]{2}:' "$SCHEME_FILE" | sed 's/: /="/;s/$/"/')"

# Map base16 to semantic roles
# base00=bg, base05=fg, base08=red, base09=orange, base0A=yellow, base0B=green
# base0C=cyan, base0D=blue, base0E=magenta, base0F=brown
# base01=bg-dark, base02=selection, base03=comments, base04=fg-dark
declare -A C=(
    [bg]="${base00:-303446}"
    [fg]="${base05:-c6d0f5}"
    [red]="${base08:-e78284}"
    [orange]="${base09:-ef9f76}"
    [yellow]="${base0A:-e5c890}"
    [green]="${base0B:-a6d189}"
    [cyan]="${base0C:-81c8be}"
    [blue]="${base0D:-8caaee}"
    [magenta]="${base0E:-ca9ee6}"
    [comments]="${base03:-737994}"
    [selection]="${base02:-414559}"
    [bright_fg]="${base04:-a5adce}"
)

STARSHIP_TOML="${HOME}/.config/starship.toml"

cat > "$STARSHIP_TOML" << EOF
# Generated by tinty starship-hook — do not edit manually

[character]
success_symbol = "[ ❯](bold #${C[green]})"
error_symbol = "[ ❯](bold #${C[red]})"

[git_branch]
symbol = " "
style = "bold #${C[yellow]}"

[time]
format = "%H:%M:%S"
style = "bold #${C[blue]}"

[username]
style_user = "bold #${C[green]}"
style_root = "bold #${C[red]}"
format = "[\$user](\$style)"
disabled = false

[hostname]
ssh_only = true
format = "[@\$hostname](bold #${C[green]})"

[directory]
style = "bold #${C[green]}"
format = "[\$path](\$style) "
truncation_length = 3
truncation_symbol = "…/"

[git_status]
conflicted = "💣"
ahead = "📤"
behind = "📥"
diverged = "😵"
untracked = "★"
stashed = "📦"
modified = ""
staged = "✓"
renamed = "🗘"
deleted = ""
style = "bold #${C[red]}"

[docker_context]
symbol = "  "
style = "bold #${C[blue]}"
format = "[\$symbol\$context](\$style)"
EOF

echo "[starship-hook] starship.toml updated" >&2
