# Catppuccin Frappe palette

[character]
success_symbol = "[ 🎏](bold #a6d189)"
error_symbol = "[ 👹](bold #e78284)"
[git_branch]
symbol = "🌿 "
style = "bold #e5c890"
[time]
format = "%H:%M:%S"
style = "bold #8caaee"
[username]
style_user = "bold #a6d189"
style_root = "bold #e78284"
format = "[$user]($style)"
disabled = false
[hostname]
ssh_only = true
format = "[@$hostname](bold #a6d189)"
[directory]
style = "bold #a6d189"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"
[git_status]
conflicted = "💣"
ahead = "📤"
behind = "📥"
diverged = "😵"
untracked = "★"
stashed = "📦"
modified = ""
staged = "✓"
renamed = "🗘"
deleted = ""
style = "bold #e78284"
[docker_context]
symbol = " 🐳 "
style = "bold #8caaee"
format = "[$symbol$context]($style)"